</$objtype/mkfile

LIB=libnsutils.$O.a
OBJ=base64.$O time.$O unistd.$O
HFILES=../include/nsutils/base64.h ../include/nsutils/endian.h ../include/nsutils/errors.h

<../../nsport.mk
<../../nsportlib.mk
